services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: team_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/team_management"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      PORT: 3501
      NODE_ENV: production
      PACE_FACTOR: 0.8
    ports:
      - "3501:3501"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3501/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: